import { createLogger } from '@/lib/logger'
import { env } from '@/lib/env'

const logger = createLogger('email:analysis-complete')

interface AnalysisCompleteParams {
  recipientEmail: string
  recipientName: string
  candidateName: string
  recommendation: string
  recommendationConfidence?: number
  sentimentScore?: number
  reportUrl: string
}

export async function sendAnalysisComplete(params: AnalysisCompleteParams): Promise<void> {
  const {
    recipientEmail,
    recipientName,
    candidateName,
    recommendation,
    recommendationConfidence,
    sentimentScore,
    reportUrl,
  } = params

  const subject = `AI Analysis Ready: ${candidateName}`

  // Determine recommendation badge color
  let recommendationColor = '#64748b'
  let recommendationBg = '#f1f5f9'

  if (recommendation.toLowerCase().includes('strong')) {
    recommendationColor = '#16a34a'
    recommendationBg = '#dcfce7'
  } else if (recommendation.toLowerCase().includes('not')) {
    recommendationColor = '#dc2626'
    recommendationBg = '#fee2e2'
  } else if (recommendation.toLowerCase().includes('consider')) {
    recommendationColor = '#f59e0b'
    recommendationBg = '#fef3c7'
  }

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #8b5cf6, #7c3aed); padding: 32px; border-radius: 12px 12px 0 0; text-align: center;">
    <h1 style="color: white; margin: 0; font-size: 24px;">AI Analysis Complete</h1>
  </div>

  <div style="background: #ffffff; padding: 32px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
    <p>Hi ${recipientName},</p>

    <p>The AI analysis for <strong>${candidateName}</strong>'s interview is now ready for your review.</p>

    <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 24px 0;">
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Candidate</td>
          <td style="padding: 8px 0; font-weight: 600;">${candidateName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Recommendation</td>
          <td style="padding: 8px 0;">
            <span style="display: inline-block; background: ${recommendationBg}; color: ${recommendationColor}; padding: 4px 12px; border-radius: 6px; font-weight: 600; font-size: 14px;">
              ${recommendation}
            </span>
          </td>
        </tr>
        ${recommendationConfidence ? `
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Confidence</td>
          <td style="padding: 8px 0; font-weight: 600;">${recommendationConfidence}%</td>
        </tr>
        ` : ''}
        ${sentimentScore !== undefined ? `
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-size: 14px;">Sentiment Score</td>
          <td style="padding: 8px 0; font-weight: 600;">${sentimentScore}/100</td>
        </tr>
        ` : ''}
      </table>
    </div>

    <div style="background: #fef9c3; border: 1px solid #fde047; border-radius: 8px; padding: 16px; margin: 24px 0;">
      <p style="margin: 0; font-size: 14px; color: #854d0e;">
        <strong>💡 Key Insights:</strong> The AI has analyzed the interview transcript, assessed technical and soft skills, identified strengths and concerns, and provided actionable recommendations for your hiring decision.
      </p>
    </div>

    <div style="text-align: center; margin: 24px 0;">
      <a href="${reportUrl}" style="display: inline-block; background: #8b5cf6; color: white; padding: 12px 32px; border-radius: 8px; text-decoration: none; font-weight: 600;">
        View Full Analysis Report
      </a>
    </div>

    <p style="font-size: 14px; color: #64748b;">
      The full analysis includes detailed competency scores, key moments from the interview, suggested follow-up questions, and more.
    </p>

    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;">

    <p style="font-size: 12px; color: #94a3b8; text-align: center;">
      This analysis was generated by VerticalHire AI. To manage your notification preferences, visit your account settings.
    </p>
  </div>
</body>
</html>`

  // Use Resend if available, otherwise log
  if (env.RESEND_API_KEY) {
    const { Resend } = await import('resend')
    const resend = new Resend(env.RESEND_API_KEY)

    await resend.emails.send({
      from: env.RESEND_FROM_EMAIL || 'notifications@verticalhire.com',
      to: recipientEmail,
      subject,
      html: htmlBody,
    })
  } else {
    logger.info({
      message: 'Would send analysis complete notification (no RESEND_API_KEY)',
      recipientEmail,
      subject,
      candidateName,
      recommendation,
      recommendationConfidence,
    })
  }
}
